### ISSUE TITLE
Nothing is shown...

### ISSUE THREAD

**Issue by big-r81** [davideberlein/kanboard-presenter#2]
Hi David,

i would like to use yor app and configured the routes.js with the server-url and the token.
My Kanboard-Version is 1.0.18.

Here is a screenshot:
![bildschirmfoto 2015-09-25 um 09 45 34](https://cloud.githubusercontent.com/assets/9985963/10095478/63c165d4-636a-11e5-856f-0ca37d5cd6a7.png)

Cheers,
Ronny

**Comment by big-r81** [comment]
[UPDATE]
after opening the url localhost:16565 the browser jumps to

http://localhost:16565/#/user/17/board/

but there is no user with this id, so nothing is shown...

Why does it show up user 17?

Cheers,
Ronny

**Comment by davideberlein** [comment]
The user 17 is preconfigured due to our project. You can change the default user in `public/js/angular/kanboard-presenter.js` line 10 or just enter a url with your user.

Cheers

David
