### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by thedaftbadger** [davideberlein/kanboard-presenter#3]
Is this still maintained? Having issues getting it to work....

![image](https://cloud.githubusercontent.com/assets/13657363/13145192/0678c994-d647-11e5-948f-705a65961fa8.png)

**Comment by davideberlein** [comment]
It has not been in development for the last month. What OS and version are you on? also which node version are you using?

**Comment by thedaftbadger** [comment]
Using node v0.10.29 on Raspian latest version

**Comment by davideberlein** [comment]
Have you tried running it on a Desktop Linux version?

**Comment by thedaftbadger** [comment]
No not yet I had a spare Pi and thought this might be a good sue for it :)

**Comment by davideberlein** [comment]
We also ran the app on a rasp however v2. I don't think a v1 is powerfull
enough to handle the UI and transformations.
In general however it should run.

**Comment by thedaftbadger** [comment]
Having issues with getting the latest Linaro SD Image, any other recommendations for Linux Distros we should use on other hardware for this project?
