### ISSUE TITLE
Filtering closed tasks

### ISSUE THREAD

**Issue by rverchere** [davideberlein/kanboard-presenter#4]
By default, all tasks are visible.

Is it possible to filter only opened tasks?

**Comment by davideberlein** [comment]
Hey, at the moment no, but feel free to add the functionality and create a pull request!

**Comment by rverchere** [comment]
Hi,

Just sent you a Pull Request concerning this!

BR

**Comment by davideberlein** [comment]
Changes look good, thx also for the docker integration. I merged your pull request.
